### ISSUE TITLE
[Spike - Backend] Analyze downloading options of the Dataset page in view mode and create spike issues

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#191]
## Overview of the Feature Request

The goal of this issue is to analyze the required backend development for #63 and create spike issues (js-dataverse and API).

## What inspired the request?

- https://github.com/IQSS/dataverse-frontend/issues/63

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/63
- https://github.com/IQSS/dataverse-frontend/issues/182

**Comment by GPortas** [comment]
I have created a new issue for dataset and datafile citation export https://github.com/IQSS/dataverse/issues/9994. I prefer to wait to analyze this implementation in more detail before creating js-dataverse issues, since I don't know yet if this will require a use case or not.

The dataset export already has a publicly accessible endpoint (as the functionality only works for public datasets), so it does not require any backend changes. Potentially this will require no use case, so no js-dataverse issue is created.

**Comment by GPortas** [comment]
**Dataset and datafile citation export**

I have created a new issue for dataset and datafile citation export: https://github.com/IQSS/dataverse/issues/9994. 

I have decided to wait to analyze this implementation in more detail before creating js-dataverse issues, since I don't know yet if this will require use case logic or not.

**Export dataset**

The dataset export already has a publicly accessible endpoint (as the functionality only works for public datasets), so it does not require any backend changes. 

At the moment I think this will not require use case, so no js-dataverse issue is created.

**Download dataset**

We need to extend the API to replicate the behavior of the Dataset Download Options of JSF.

I have created an issue (80) intended to be a parent issue of more spikes: https://github.com/IQSS/dataverse/issues/9996

An initial analysis spike issue has been created to better understand the scope of the necessary development and creation of the rest of the spikes: https://github.com/IQSS/dataverse/issues/9997

** Created backend spike issues **

- https://github.com/IQSS/dataverse/issues/9994
- https://github.com/IQSS/dataverse/issues/9996
- https://github.com/IQSS/dataverse/issues/9997

**Comment by GPortas** [comment]
**Dataset and datafile citation export**

<img width="497" alt="filecitation" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/7ad91309-9b08-48e4-a685-a74fced081a2">

![citation](https://github.com/IQSS/dataverse-frontend/assets/17010447/fef0f0de-04c9-4100-a8d6-fc4c6e1e49c9)

I have created a new issue for dataset and datafile citation exporting through API: https://github.com/IQSS/dataverse/issues/9994. 

I have decided to wait to analyze this implementation and confirm the needs of the frontend before creating js-dataverse issues, since I don't know yet if this will require use case logic or not.

**Export dataset metadata**

<img width="1158" alt="exportmetadata" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/5b047cad-bf0f-48d4-8d11-cf375c5e39ce">

The dataset export already has a publicly accessible endpoint (as the functionality only works for public datasets), so it does not require any backend changes: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java#L279

At the moment I think this will not require use case, so no js-dataverse issue is created.

**Download dataset (download all files)**

![downloadallfiles](https://github.com/IQSS/dataverse-frontend/assets/17010447/ae8e790b-f82a-4b28-ae34-79a742ca89f0)

<img width="368" alt="downloadallfilestab" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/b7632149-5169-4b52-ab88-96c6953b1ad4">


We need to extend the API to replicate the behavior of the Dataset Download Options (all dataset files download) of JSF.

Given the current uncertainty on this, I have created an issue (80) intended to be a parent issue of more spikes: https://github.com/IQSS/dataverse/issues/9996

An initial analysis spike issue has been created to better understand the scope of the necessary development and creation of the rest of the spikes: https://github.com/IQSS/dataverse/issues/9997

**Download single file**

<img width="378" alt="downloadfile" src="https://github.com/IQSS/dataverse-frontend/assets/17010447/50076f56-443c-4a31-9d41-1f5765c136a9">

There is already an endpoint under the access API to download a specific file. This endpoint is consumed from JSF.

This operation seems less complex than the previous one (multiple files). See: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java#L88

At the moment I am not going to create any API spike issue since we will possibly use the existing API as it is.

I am not sure yet if js-dataverse logic will be necessary. So I am not going to create any js-dataverse spike until we better understand the needs of the frontend.

**Missing properties for frontend checks and display**

Some of these properties are already detected and mentioned on https://github.com/IQSS/dataverse-frontend/issues/182#issuecomment-1742726041. For example: fileMetadata.dataFile.filePackage, fileMetadata.dataFile.originalFormatLabel, systemConfig.HTTPDownload..

These properties will potentially require extending the current API payloads and js-dataverse and models, and possibly creating new API endpoints and use cases.

Although @MellyGray has already detected some properties that we will need, I think we can follow the common approach taken so far. We can mock these values in the SPA until we have a more complete list of all the properties we need to finally create more complete and precise API and js-dataverse extension issues.

**Created backend spike issues**

- https://github.com/IQSS/dataverse/issues/9994
- https://github.com/IQSS/dataverse/issues/9996
- https://github.com/IQSS/dataverse/issues/9997

**Comment by sekmiller** [comment]
Moving this along. Looks like all of the points are addressed with the additional api issues added as noted above.
