### ISSUE TITLE
Github Action failing for e2e test

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#213]
The e2e test is consistently failing in Github Actions because the wait for containers to be ready times out. 
Here is an example action- 
https://github.com/IQSS/dataverse-frontend/actions/runs/6709488248/job/18232645812
and output:
![Screenshot 2023-11-01 at 10 33 09 AM](https://github.com/IQSS/dataverse-frontend/assets/675224/7631fcb2-3351-4bf0-a492-af3c0a4b34bb)

**Comment by pdurbin** [comment]
As promised at standup, I added this to the agenda for tomorrow's [containerization](https://ct.gdcc.io/) meeting: https://docs.google.com/document/d/1iE-DHDxWNK6OYNgqnLPo3i6pIH6Danw5rysXL_COjVc/edit?usp=sharing

**Comment by pdurbin** [comment]
> I would suggest dumping a copy of the logs so we can determine what's failing.

I just made a pull request for this:

- #214

**Comment by pdurbin** [comment]
e2e tests are failing because deployment of the Dataverse war file is failing with `Boot Command deploy failed PlainTextActionReporterFAILUREDescription: deploy AdminCommandError occurred during deployment: Exception while loading the app : jakarta.ejb.CreateException: Initialization failed for Singleton ConfigCheckService.`

See logs.tgz at https://github.com/IQSS/dataverse-frontend/actions/runs/6723081302?pr=214

**Comment by pdurbin** [comment]
Fixed by this PR:

- #215

Closing. Thanks, @poikilotherm ❤️ !

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse/pull/10025
