### ISSUE TITLE
Cypress timing error in Dataset e2e test

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#236]
There is a timing error that happens intermittently in the e2e test, so far I've only seen it happening in Github, not locally.  It is in Dataset.spec.tsx, in the 'loads the restricted files when the user is logged in as owner', test.  Attached is the log information from the gihub action. The Cypress error message suggests that there is an action chained after click() in the code, but the test doesn't have that, so there must be other code triggering it.

Here is an action where it is happening: https://github.com/IQSS/dataverse-frontend/actions/runs/6905396784.
Attached are details from the Github action log.
<img width="1023" alt="Screenshot 2023-11-20 at 1 59 28 PM" src="https://github.com/IQSS/dataverse-frontend/assets/675224/810620ba-1f36-4a81-8cf6-d286e9f476a5">
<img width="1102" alt="Screenshot 2023-11-20 at 1 59 07 PM" src="https://github.com/IQSS/dataverse-frontend/assets/675224/60c2a964-c151-49fe-914a-f5ed4c8f8200">

**Comment by MellyGray** [comment]
@ekraffmiller, I've identified that this issue arises due to the dropdown being rerendered. This occurs because there's a hook checking with the API for user permissions to download files. Sometimes, Cypress is faster than the API response, leading to Cypress clicking the dropdown, but the subsequent API response triggers a rerender, closing the dropdown again.

While I could attempt to address this in the test, I believe it's more effective to fix the component behavior. Similar to how dataset permissions are included in the Dataset model, I propose implementing the same approach for file permissions. This way, file permissions would be checked during page initialization rather than when clicking the dropdown.

I'd like to hear your thoughts before I jump into applying a significant refactor of the file model. What do you think?
