### ISSUE TITLE
Analyze Storybook Testing Capabilities for UI Testing Integration

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse-frontend#27]
## Overview of the Feature Request
As part of our testing efforts, we want to analyze the capabilities of Storybook for UI testing integration. The aim is to determine if it makes sense to integrate UI tests with Storybook, and if so , how should we do it.

A part from that we want to check if Cypress tests can be automatically generated using Storybook

We already have unit tests with Vite and e2e tests with Cypress. We also have the coverage check using Vitest report. We need to check if it makes sense to change this tools by Storybook testing tools.

## What inspired the request?
- [Storybook 7 event ](https://www.youtube.com/watch?v=P0hJm5v8TJw)
- Frontend subgroup weekly meeting

## What existing behavior do you want changed?
This issue want change any behaviour, it's an analysis.

## Any brand new behavior do you want to add to Dataverse?
None

## Any open or closed issues related to this feature request?

- #20 
- #19

**Comment by mreekie** [comment]
new sprint:
- Got the testing options figured out.
- Next step is decision.
- 33 to 10

**Comment by ekraffmiller** [comment]
After reviewing the options, we've decided to use Cypress component testing, with the optional use of Storybook Interaction tests to help demonstrate component behavior within Storybook.
A summary document of the analysis, with pros and cons of the different option is here: https://docs.google.com/document/d/1qEL0s2lFP6c-hRSdQkRCxI5Qt8dBYXQoJdyUekw1ZVw/edit?usp=sharing

The example LoginForm component that we used to analyze the testing options is in this branch: https://github.com/IQSS/dataverse-frontend/tree/feature/component-testing
(Note that this branch is example code only, and shouldn't be merged into the develop branch when this issue is closed.
